FROM silkeh/clang:9

RUN apt-get update && apt-get install -y python3 python3-pip
# COPY src/requirements/ /requirements/
# RUN pip install --upgrade pip && pip install -r /requirements/deploy.txt
# RUN pip3 install --upgrade pip && pip3 install antlr4-python3-runtime==4.9.2 click==8.0.3
