version: "3.9"

services:

  compiler:
    build:
      context: .
    # restart: "${DOCKER_RESTART:-unless-stopped}"
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash
