//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\User\Documents\GitHub\della-compiler\src\app\tinyc\frontend\tinyc.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="tinycParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface ItinycListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] tinycParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] tinycParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] tinycParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] tinycParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.paren_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParen_expr([NotNull] tinycParser.Paren_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.paren_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParen_expr([NotNull] tinycParser.Paren_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] tinycParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] tinycParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest([NotNull] tinycParser.TestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest([NotNull] tinycParser.TestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.sum_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSum_([NotNull] tinycParser.Sum_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.sum_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSum_([NotNull] tinycParser.Sum_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] tinycParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] tinycParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.id_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId_([NotNull] tinycParser.Id_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.id_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId_([NotNull] tinycParser.Id_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] tinycParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] tinycParser.IntegerContext context);
}
