//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\User\Documents\GitHub\della-compiler\src\app\tinyc\frontend\tinyc.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ItinycListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class tinycBaseListener : ItinycListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] tinycParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] tinycParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] tinycParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] tinycParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.paren_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParen_expr([NotNull] tinycParser.Paren_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.paren_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParen_expr([NotNull] tinycParser.Paren_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] tinycParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] tinycParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTest([NotNull] tinycParser.TestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTest([NotNull] tinycParser.TestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.sum_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSum_([NotNull] tinycParser.Sum_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.sum_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSum_([NotNull] tinycParser.Sum_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] tinycParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] tinycParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.id_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId_([NotNull] tinycParser.Id_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.id_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId_([NotNull] tinycParser.Id_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="tinycParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] tinycParser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="tinycParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] tinycParser.IntegerContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
