FROM python:3.9

WORKDIR /app

# COPY src/requirements/ /requirements/
# RUN pip install --upgrade pip && pip install -r /requirements/deploy.txt
RUN pip install --upgrade pip && pip install antlr4-python3-runtime==4.9.2 click==8.0.3


CMD ["/bin/bash"]
