THUNDER_REFS = [
    'Jaga',
    'Lion-O',
    'Panthro',
    'Tygra',
    'Cheetara',
    'WilyKit and WilyKat',
    'Bengali',
    'Lynx-O',
    'Pumyra',
    'Claudus',
    'Jagara',
    'Snarf',
    'Snarfer',
    'Warrior Maidens',
    'Wolos',
    'Bolkins',
    'Tabbuts',
    'Fishmen',
    'Elephants',
    'Dogs',
    'Birds',
    'Crownan',
    'Dr. Dometome',
    'Hachiman',
    'Mandora',
    'Mumm-Rana',
    'Snowman',
    'Snowmeow',
    'Sondora',
    'Turmagar',
    'Unicorn Keepers',
    'Wizz-Ra',
    'Char',
    'Screwloose',
    'Antagonists',
    'Mumm-Ra',
    'Ma-Mutt',
    'The Mutants',
    'Slithe',
    'Khamai',
    'Kask',
    'Sauro',
    'Jackalman',
    'Monkian',
    'Vultureman',
    'Ratar-O',
    'Mordax',
]
